version: '3'

services:
  postgres:
    image: 'postgres'
    environment:
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_DB=${POSTGRES_DB}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
    expose:
      - '5432'
    ports:
      - '5432:5432'
